Use cpu wheel for torchvision (#155)
Making it compatible with the installed torch
version. Addresses build failures of the kind:

RuntimeError: operator torchvision::nms does not exist

Also, remove unnecessary s3torchconnector version
constraint.

Co-authored-by: Vishal Gowda <vgd@amazon.com>