Use cpu wheel for torchvision
Making it compatible with the installed torch
version. Addressed build failures of the kind:

RuntimeError: operator torchvision::nms does not exist

Also, remove unnecessary s3torchconnector version
constraint.